"""Diagnose entry-vs-trade disconnects in any generated strategy.

This script answers "why didn't my strategy trade as much as I expected?"
by wrapping the strategy's on_bar method, running it through the real
backtester (with the same session-reset semantics production uses), and
summarizing what the engine actually did at each bar:

  * how many bars fed into on_bar
  * how many of those had a position already open (entries can't fire
    while a position is open in single-position strategies)
  * how many on_bar calls returned at least one Order
  * how many of those Orders became actual closed trades

This view is complementary to `diagnose_signal_frequency` (which counts
clause hits in the DSL). When the two disagree, the gap is usually:

  * indicator warm-up (period exceeds session length) — the diagnostic
    counts hits because it walks all bars; the backtester sees None
    because session_bars resets
  * position-open exclusion — entries can't fire while open
  * walk-forward windowing — eval only counts trades in OOS windows

This script uses the backtester directly with NO walk-forward, so the
counts here are over the full train+test slice. Trade counts will
typically be higher than what a walk-forward eval reports.

Usage:
  ./venv/bin/python scripts/diagnose_disconnect.py \\
      --strategy ZscoreBbMeanReversion --symbol AMD

Origin: written 2026-04-28 to investigate the entry-fires-but-no-trades
disconnect in the post-Phase-3-fix demo (see commits f84fbdf..0b2897f).
The investigation surfaced that strategies declaring timeframes=['1d']
were getting 5m bars with session-resets, so daily-period indicators
never warmed up. Fix #1 + Fix #5 addressed the root cause; this script
remains as a general-purpose debugging tool for future disconnects.
"""

from __future__ import annotations

import argparse
import importlib
import sys
from collections import Counter
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "src"))
sys.path.insert(0, str(_ROOT))

from engine.backtester import BacktestConfig, run_backtest
from engine.session import RegularTradingHours
from evaluation.splits import train_test_load


def _camel_to_snake(name: str) -> str:
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def _import_strategy(class_name: str):
    """Import a strategy class from strategies.generated by CamelCase name."""
    snake = _camel_to_snake(class_name)
    module = importlib.import_module(f"strategies.generated.{snake}")
    return getattr(module, class_name)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--strategy", required=True,
                        help="CamelCase class name, e.g. ZscoreBbMeanReversion")
    parser.add_argument("--symbol", required=True, help="e.g. AMD")
    args = parser.parse_args()

    strategy_cls = _import_strategy(args.strategy)
    strategy = strategy_cls()
    declared = list(getattr(strategy, "timeframes", []) or [])
    if len(declared) != 1:
        sys.exit(
            f"Cannot diagnose multi-timeframe strategy {args.strategy} "
            f"(declared timeframes={declared}). Phase 3 single-timeframe only."
        )
    bar_tf = declared[0]

    bars_df = train_test_load(args.symbol, target_timeframe=bar_tf)
    print(f"Loaded {len(bars_df)} {bar_tf} bars for {args.symbol}")
    print(f"Date range: {bars_df['timestamp'].iloc[0]} → {bars_df['timestamp'].iloc[-1]}")
    print(f"Strategy declares timeframes: {declared}")
    print()

    log: list[dict] = []
    orig_on_bar = strategy.on_bar

    def wrapped(bar, position, context):
        n_recent = len(context.recent(200))
        orders = orig_on_bar(bar, position, context)
        log.append({
            "ts": bar.timestamp,
            "n_recent": n_recent,
            "position_open": position is not None,
            "n_orders": len(orders) if orders else 0,
        })
        return orders

    strategy.on_bar = wrapped

    cfg = BacktestConfig(
        starting_capital=10_000,
        commission=0.0,
        slippage=0.01,
        realistic_fills=True,
        session=RegularTradingHours(),
        bar_timeframe=bar_tf,
    )
    result = run_backtest(args.symbol, bars_df, strategy, cfg)

    n_total = len(log)
    n_position_open = sum(1 for r in log if r["position_open"])
    n_emitted = sum(1 for r in log if r["n_orders"] > 0)
    n_orders = sum(r["n_orders"] for r in log)
    n_trades = len(result.portfolio.trades)
    sess_lengths = Counter(r["n_recent"] for r in log)
    max_session_bars = max(sess_lengths) if sess_lengths else 0
    intraday = bar_tf in ("1m", "5m", "15m", "30m", "1h", "4h")

    print("=" * 78)
    print(f"BACKTEST DIAGNOSTIC — {args.symbol} / {args.strategy}")
    print("=" * 78)
    print(f"  Bars on_bar called:                {n_total:>10}")
    print(f"  Max bars in any context window:    {max_session_bars:>10}  "
          f"({'session-resets active' if intraday else 'continuous (daily+ session)'})")
    print(f"  Bars where position was open:      {n_position_open:>10}  "
          f"({n_position_open/n_total:.1%})")
    print()
    print(f"  on_bar calls that emitted >=1 order: {n_emitted:>8}")
    print(f"  Total orders emitted:              {n_orders:>10}")
    print(f"  Trades closed in BacktestResult:   {n_trades:>10}")
    print()
    if n_orders > 0 and n_trades == 0:
        print("  WARNING: orders emitted but zero trades closed. Check "
              "fill semantics in engine.backtester._fill_market_entry.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
